const diagnosiGestioneTitle = 'Diagnosi e gestione neonatale Sindrome di Crisponi';

const diagnosiGestioneParagraphs = [
  'La sindrome di Crisponi si manifesta già dalla nascita. Il piccolo presenta subito dopo la nascita difficoltà respiratorie con crisi di apnea e abbondante salivazione. Durante il pianto che appare soffocato presenta trisma serrato e contrattura dei muscoli mimici del volto, atteggiamento in opistotono, vi è difficoltà alla deglutizione e presenta abbondante salivazione, si presentano delle crisi di apnee più o meno prolungate cui si associa modesta cianosi. Lasciato calmare, il piccolo riprende un atteggiamento sereno, il respiro appare regolare le contrazioni non sono più evidenti. Ad una attenta osservazione si osserva un atteggiamento a pugnetto delle mani con il 3 e 4° dito fortemente flesso sul palmo e le altre dita sovrapposte, talvolta sono presenti anche anomalie di inserzione delle dita dei piedi. A carico del volto sono presenti anche alcuni aspetti peculiari come guance piene, filtro lungo, narici anteverse, micrognatia. Le sollecitazioni e gli stimoli dolorosi che determinano il pianto evocano la ripresa delle contratture, le crisi di apnea e la abbondante salivazione. Anche i tentativi di alimentazione risultano difficoltosi per la mancanza di stimolo della deglutizione e della suzione valida. Durante il pianto si manifestano anche atteggiamento in opistotono, movimenti di torsione del tronco e movimenti afinalistici degli arti. È necessario mantenere il bambino non eccessivamente coperto in un ambiente rilassante, con scarsi stimoli sonori, riduzione delle manipolazioni, anche durante la pulizia e il cambio dei pannolini. La alimentazione dovrà essere effettuata per gavage con sondino nasogastrico a permanenza, e con l’uso della pompa per l’alimentazione.',
  'Poiché la maggioranza di questi bambini dopo qualche giorno dalla nascita presenta febbre continuo remittente sui 38°C con puntate anche oltre 40°C è opportuno ridurre la temperatura ambiente non oltre i 20°C. Per una attenta sorveglianza è opportuno tenere il bambino col minimo di vestiario in una termoculla possibilmente spenta. Compatibilmente con le esigenze del reparto è preferibile che il bambino abbia una stanza completamente a disposizione con continua sorveglianza infermieristica. Il piccolo deve essere sempre monitorizzato per la frequenza cardiaca, respiratoria, rilevazione transcutanea della saturazione di ossigeno, rilevazione della temperatura cutanea. L’alimentazione con sondino nasogastrico tramite pompa di alimentazione. Per evitare che le mani rimangano sempre chiuse a pugnetto si consiglia l’uso di un palmarino. La presenza dei genitori è indispensabile, devono poter accedere al reparto in qualsiasi momento della giornata per permettere loro di occuparsi del bimbo secondo le modalità che verranno suggerite dal personale medico, in base soprattutto allo stato di salute del piccolo. La vicinanza dei genitori servirà sicuramente al neonato ma anche ai genitori stessi.',
  'Durante la degenza è opportuno che i genitori imparino a sondare il bambino poiché le difficoltà alla alimentazione spontanea tendono a perdurare per mesi, i genitori devono anche impratichirsi nell’uso dell’aspiratore e nella gestione della somministrazione dell’ossigeno.',
  'In questi pazienti che non sono in grado di nutrirsi autonomamente per bocca si può proporre la Gastrostomia Endoscopica Percutanea, detta anche PEG, che è una tecnica che consente la nutrizione enterale in alternativa al sondino nasogastrico.',
  'La PEG permette un notevole miglioramento della qualità della vita rispetto al sondino naso gastrico che è spesso poco tollerato e che presenta numerosi svantaggi sul paziente.',
  'Di fronte al sospetto di un neonato con la Sindrome di Crisponi, è opportuno che il personale medico e infermieristico venga edotto sulla evoluzione clinica cui andranno incontro questi piccoli bambini e del rischio elevato di mortalità che possono presentare. Il neonato dovrà essere collocato in ambienti strutturalmente idonei: nel reparto di Patologia neonatale o, in caso di necessità di cure intensive, in una zona separata e specificatamente dedicata al paziente pediatrico nell’ambito della Terapia Intensiva Neonatale. Per ridurre i disagi si consiglia di mantenere la temperatura dell’ambiente tra i 18-20°C possibilmente con aria condizionata sempre accesa nei mesi estivi e spegnimento o regolazione del riscaldamento nei mesi invernali.',
  'La dotazione di apparecchiature per il posto letto comprende, oltre a sistemi di infusione di precisione anche per piccolissimi volumi, un monitor, montato sul letto. Assicura il monitoraggio on line dei parametri di elettrocardiogramma, frequenza Cardiaca, frequenza respiratoria, pressione arteriosa incruenta e cruenta, pressione venosa centrale, saturazione dell’ossigeno e dell’anidride carbonica di fine espirazione, temperatura corporea.',
  'La dotazione del singolo posto letto è completata da un sistema di riscaldamento-raffreddamento ad aria, materassino antidecubito con variazione programmata della zona corporea di appoggio, sistema di erogazione di ossigeno a concentrazione definita e a diversa temperatura con nebulizzazione.',
  'Il piccolo deve essere sistemato in una termoculla possibilmente spenta col minimo di abbigliamento per una costante osservazione. È necessario che venga continuamente monitorizzato per la valutazione cardiorespiratoria, saturazione dell’ossigeno. Per l’alimentazione si consiglia già subito dopo la nascita l’applicazione di un sondino naso-gastrico a permanenza e l’utilizzo di una pompa di alimentazione per la somministrazione del latte.',
  'È opportuno avere sempre a disposizione pompa a vuoto per la aspirazione delle mucosità, sondini per aspirazione, cannule orofaringee di Majo, maschere di ventilazione con pallone Ambu per manovre di rianimazione di emergenza.',
  'Poiché sappiamo che ogni stimolo dolorifico scatena gli accessi di contrattura con associate crisi respiratorie è necessario intervenire sul dolore. Il protocollo dell’analgesia nel neonato prevede diverse situazioni che vanno dal semplice distress del neonato al posizionamento di sondini, puntura del tallone, alle manovre invasive quali: intubazione, aspirazione endo-tracheale, rachicentesi, posizionamento catetere centrale, ecc. Per ognuna di queste situazioni è previsto un intervento di tipo analgesico, che va dalle semplici coccole e massaggi, alla somministrazione di sucrosio al 12% con tettarella, all’uso di pomate anestetiche quali l’EMLA, fino alla somministrazione di farmaci (Fentanyl, Remifentanyl, Morfina ecc.).',
];

export const diagnosiGestione = {
  it: {
    sindromeDiagnosiButton: 'Diagnosi e Gestione',
    diagnosiGestioneTitle,
    diagnosiGestioneParagraphs,
  },
  en: {
    sindromeDiagnosiButton: 'Diagnosis and Management',
    // Not yet translated to English - showing the Italian text until a translation is provided.
    diagnosiGestioneTitle,
    diagnosiGestioneParagraphs,
  },
};
